### ISSUE TITLE
nativescript specific version 

### ISSUE THREAD

**Issue by rafilkmp3** [hrueger/setup-nativescript#6]
Would be nice to be able to choose version
```
- name: Setup nativescript with specific version 
  uses:  hrueger/setup-nativescript@v1.0.1
  with:
    nativescript-version: '6.5'
```

**Comment by hrueger** [comment]
@rafilkmp3 That would be useful, for sure.
Shouldn't be too hard to implement. I'll look into that once I find some time.

As a workaround, you could simply install another version (`npm i -g nativescript@6.5`) after this action.

**Comment by rafilkmp3** [comment]
@hrueger Thanks a lot for a quick response and for workarround and this can get too the tag hacktoberfest

**Comment by hrueger** [comment]
Added in ee2db8cb91a159ef25dbc30965a80e455d41e75b 

You should be able to use this in the latest version (`v1.1.0`):
```yml
- uses: hrueger/setup-nativescript@v1.1.0
  with:
    nativescript-version: '7.0.10'
```
